services:
  gin-mysql:
    image: "mysql:5.7"
    environment:
      - "MYSQL_DATABASE=test"
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - gin-network

  gin-redis:
    image: "redis:6.0.9"
    ports:
      - "6379:6379"
    networks:
      - gin-network

networks:
  gin-network:
